export const about_cover = "https://openmoonray.org/images/d3_hiccup2.png"
export const about_displayfilters1 = "https://openmoonray.org/images/display_filters.png"
export const about_displayfilters2 = "https://openmoonray.org/images/display_filters2.png"
export const about_layerableminerals = "https://openmoonray.org/images/layering.png"
export const about_lightfilter1 = "https://openmoonray.org/images/orthocookie1.png"
export const about_lightfilter2 = "https://openmoonray.org/images/perspcookie1.png"
export const about_lightfilter3 = "https://openmoonray.org/images/orthocookie2.png"
export const about_lightfilter4 = "https://openmoonray.org/images/perspcookie2.png"
export const about_lightpath = "https://openmoonray.org/images/aovs.png"
export const about_pathtracing = "https://openmoonray.org/images/vectorized.png"
export const about_profileviewer = "https://openmoonray.org/images/profile_viewer.png"
export const documentation_cover = "https://openmoonray.org/images/badguys_loot.png"
export const documentation_movie1 = "https://openmoonray.org/images/posters/bg2.png"
export const documentation_movie2 = "https://openmoonray.org/images/posters/bg_liars.png"
export const documentation_movie3 = "https://openmoonray.org/images/posters/wildrobot.png"
export const documentation_movie4 = "https://openmoonray.org/images/posters/kung_fu_panda_4.jpg"
export const documentation_movie5 = "https://openmoonray.org/images/posters/trolls_band_together.jpg"
export const documentation_movie6 = "https://openmoonray.org/images/posters/rgtk-poster.jpg"
export const documentation_movie7 = "https://openmoonray.org/images/posters/puss_in_boots_the_last_wish.jpg"
export const documentation_movie8 = "https://openmoonray.org/images/posters/the_bad_guys.jpg"
export const documentation_movie9 = "https://openmoonray.org/images/posters/trolls_holiday_in_harmony.jpg"
export const documentation_movie10 = "https://openmoonray.org/images/posters/boss_baby_family_business.jpg"
export const documentation_movie11 = "https://openmoonray.org/images/posters/to_gerard.jpg"
export const documentation_movie12 = "https://openmoonray.org/images/posters/the_croods_new_age.jpg"
export const documentation_movie13 = "https://openmoonray.org/images/posters/trolls_world_tour.jpg"
export const documentation_movie14 = "https://openmoonray.org/images/posters/abominable.jpg"
export const documentation_movie15 = "https://openmoonray.org/images/posters/marooned.jpg"
export const documentation_movie16 = "https://openmoonray.org/images/posters/how_to_train_your_dragon_hidden_world.jpg"
export const documentation_movie17 = "https://openmoonray.org/images/posters/bilby.jpg"
export const download_cover = "https://openmoonray.org/images/d3_flight.png"
export const faq_cover = "https://openmoonray.org/images/trolls2_beach.png"
export const favicon = "https://openmoonray.org/images/favicon.png"
export const home_cover = "https://openmoonray.org/images/badguys_river2.png"
export const home_paper = "https://openmoonray.org/images/paper.png"
export const home_puss_in_boots = "https://openmoonray.org/images/puss_in_boots.jpeg"
export const home_cloud_guy = "https://openmoonray.org/images/trolls2_cloudguy.png"
export const license_cover = "https://openmoonray.org/images/trolls.png"
export const moonray_logo = "https://openmoonray.org/images/nav.png"
export const footer_logo = "https://openmoonray.org/images/dwa.png"








